
CC = 		../ASM

TARGET = 	out.gen

LIBDIR =	../xgenlib/

LIB	=		../xgenlib/array.x \
			../xgenlib/interaction.x \
			../xgenlib/manager.x \
			../xgenlib/math.x \
			../xgenlib/object.x \
			../xgenlib/process.x \
			../xgenlib/std.x \
			../xgenlib/module.x \
			../xgenlib/class.x \
			../xgenlib/descriptor.x \
			../xgenlib/link.x \
			../xgenlib/chain.x


SRC =		network.x


BEGIN =		main

all:
	$(CC) $(BEGIN) $(TARGET) $(SRC) $(LIB)






