
CC = 		../ASM

TARGET = 	out.gen

LIB	=	lib/std.x \
		lib/object.x \
		lib/array.x \
		lib/math.x \


SRC =		test.x \
		neuron.x \
		synapse.x \
		layer.x \
		brain.x \


BEGIN =		TEST_NEURON

all:
	$(CC) $(BEGIN) $(TARGET) $(SRC) $(LIB)






