
CC = 		../ASM

TARGET = 	out.gen

SRC =		cell.x \
		chan.x \
		utils.x \
		nucleus.x \
		link.x \
		cytosol.x \
		axon.x \


BEGIN =		MAIN

all:
	$(CC) $(BEGIN) $(TARGET) $(SRC)
	$(CC) Test test.gen test.x chan.x utils.x




