
CC = 		../../build/asm

TARGET = 	car.gen

LIB =		../../lib/obj.x \
			../../lib/utils.x

SRC =		test.x \
			vehicle.x \
			car.x \
			truck.x \

BEGIN =		test

all:
	$(CC) $(BEGIN) $(TARGET) $(SRC) $(LIB)






