
CC = 		../ASM

TARGET = 	out.gen

LIB	=	lib/std.x \
		lib/object.x \
		lib/array.x \
		lib/math.x \
		lib/interaction.x \
		lib/process.x


SRC =		t2.x #test.x \ main.x


BEGIN =		MAIN

all:
	$(CC) $(BEGIN) $(TARGET) $(SRC) $(LIB)






