
CC = 		../ASM

TARGET = 	out.gen

SRC =		cell.x \
		axon.x \
		nucleus.x \
		extern.x \
		link.x \
		cytosol.x 

INTER =		nucleus.xss \
		cell.xss \
		extern.xss \
		link.xss \
		axon.xss \
		chan.xss \

BEGIN =		CENTER

all:
	$(CC) $(BEGIN) $(TARGET) $(SRC) $(INTER)
