MAIN<
0 (
	set ( @A 0 )
	add ( @A 10 )
	sup ( @A 0 add ( @A 1 ) set ( @A 10 ) )
	add ( @A 10 )
	sup ( @A 0 add ( @A 2 ) set ( @A 10 ) )
	sup ( @A 0 sup ( @A 0 add ( @A 11 ) ) )
	add ( @A 10 )
	set ( @A 0 )
        add ( @A 10 )
        sup ( @A 0 add ( @A 1 ) set ( @A 10 ) )
        add ( @A 10 )
        sup ( @A 0 add ( @A 2 ) set ( @A 10 ) )
        sup ( @A 0 sup ( @A 0 add ( @A 11 ) ) )
        add ( @A 10 )
	set ( @A 0 )
        add ( @A 10 )
        sup ( @A 0 add ( @A 1 ) set ( @A 10 ) )
        add ( @A 10 )
        sup ( @A 0 add ( @A 2 ) set ( @A 10 ) )
        sup ( @A 0 sup ( @A 0 add ( @A 11 ) ) )
        add ( @A 10 )
        set ( @A 0 ) 
        add ( @A 10 )
        sup ( @A 0 add ( @A 1 ) set ( @A 10 ) )
        add ( @A 10 )
        sup ( @A 0 add ( @A 2 ) set ( @A 10 ) )
        sup ( @A 0 sup ( @A 0 add ( @A 11 ) ) )
        add ( @A 10 )
	set ( @A 0 )
        add ( @A 10 )
        sup ( @A 0 add ( @A 1 ) set ( @A 10 ) )
        add ( @A 10 )
        sup ( @A 0 add ( @A 2 ) set ( @A 10 ) )
        sup ( @A 0 sup ( @A 0 add ( @A 11 ) ) )
        add ( @A 10 )
        set ( @A 0 )
        add ( @A 10 )
        sup ( @A 0 add ( @A 1 ) set ( @A 10 ) )
        add ( @A 10 )
        sup ( @A 0 add ( @A 2 ) set ( @A 10 ) )
        sup ( @A 0 sup ( @A 0 add ( @A 11 ) ) )
        add ( @A 10 )
        set ( @A 0 )
        add ( @A 10 )
        sup ( @A 0 add ( @A 1 ) set ( @A 10 ) )
        add ( @A 10 )
        sup ( @A 0 add ( @A 2 ) set ( @A 10 ) )
        sup ( @A 0 sup ( @A 0 add ( @A 11 ) ) )
        add ( @A 10 )
        set ( @A 0 ) 
        add ( @A 10 )
        sup ( @A 0 add ( @A 1 ) set ( @A 10 ) )
        add ( @A 10 )
        sup ( @A 0 add ( @A 2 ) set ( @A 10 ) )
        sup ( @A 0 sup ( @A 0 add ( @A 11 ) ) )
        add ( @A 10 )
)
>
