
CC = 		../ASM

SENSOR = 	sensor.gen

ACTOR =		actor.gen

LIB =		../testlib3/lib/utils.x \
		../testlib3/lib/interactions.x \
		../testlib3/dendrite.x \
		../testlib3/axon.x

SRCS =		test.x

all:
	$(CC) ACTOR $(ACTOR) $(SRCS) $(LIB)
	$(CC) SENSOR $(SENSOR) $(SRCS) $(LIB)






